"""initial schema database

Revision ID: 001
Revises: 
Create Date: 2016-08-13 12:00:36.929074

"""

# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_type',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('unit', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_type',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_table('product',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('price', sa.Float(precision=2), nullable=False),
        sa.Column('unit_for_price', sa.Integer(), nullable=False),
        sa.Column('price_type_id', sa.Integer(), nullable=True),
        sa.Column('product_type_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['price_type_id'], ['price_type.id'], ),
        sa.ForeignKeyConstraint(['product_type_id'], ['product_type.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    op.drop_table('product_type')
    op.drop_table('price_type')
    ### end Alembic commands ###
